---

- name: Install vault_extra_packages
  ansible.builtin.pkgng:
    name: "{{ vault_extra_packages }}"

- name: Install vault
  ansible.builtin.pkgng:
    name: "{{ vault_package }}"
    state: present

- name: Patch security/vault/files/vault.in
  ansible.builtin.patch:
    src: patch-FreeBSD-rcd
    dest: /usr/local/etc/rc.d/vault

- name: "Create /etc/rc.conf.d/{{ vault_service }}"
  ansible.builtin.template:
    src: FreeBSD.rc.conf.j2
    dest: "/etc/rc.conf.d/{{ vault_service }}"
  notify:
    - Restart vault
