---
# tasks file for ansible-role-vault

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create vault_root_dir
  file:
    path: "{{ vault_root_dir }}"
    mode: 0755
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    state: directory
  notify: Restart vault

- name: Create vault_root_subdirs
  file:
    path: "{{ vault_root_dir }}/{{ item }}"
    mode: 0755
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    state: directory
  notify: Restart vault
  with_items: "{{ vault_root_subdirs }}"

- name: Create vault.conf
  template:
    src: vault.hcl.j2
    dest: "{{ vault_conf_file }}"
    # TODO validate
    # validate: echo %s
  notify: Restart vault

- name: Start vault
  service:
    name: "{{ vault_service }}"
    enabled: true
    state: started

- name: Wait for vault to start
  wait_for:
    host: "{{ vault_listen_addr }}"
    port: "{{ vault_listen_port }}"
    delay: 3

- name: See init status
  command: vault operator init -status
  environment:
    VAULT_ADDR: "{{ vault_listen_scheme }}://{{ vault_listen_addr }}:{{ vault_listen_port }}"
  register: __register_vault_operator_init
  changed_when: false
  # 0 == initialized
  # 1 == error
  # 2 == not initialized
  failed_when: __register_vault_operator_init['rc'] == 1

- name: Include init.yml
  include_tasks: init.yml
  when: __register_vault_operator_init['rc'] == 2
