---
# tasks file for ansible-role-vault

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create vault_root_dir
  file:
    path: "{{ vault_root_dir }}"
    mode: 0755
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    state: directory
  notify: Restart vault

- name: Create vault_root_subdirs
  file:
    path: "{{ vault_root_dir }}/{{ item }}"
    mode: 0755
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    state: directory
  notify: Restart vault
  with_items: "{{ vault_root_subdirs }}"

- name: Create vault.conf
  template:
    src: vault.hcl.j2
    dest: "{{ vault_conf_file }}"
    validate: echo %s
  notify: Restart vault

- name: Start vault
  service:
    name: "{{ vault_service }}"
    enabled: true
    state: started
